enum MoneyTreeState {
    SPLASH = "SPLASH",
    INTRO = "INTRO",
    CHOOSE_ENVELOPE = "CHOOSE_ENVELOPE",
    INTRO_ROUND = "INTRO_ROUND",
    QUESTION = "QUESTION",
    ANSWER = "ANSWER",
    END_ROUND = "END_ROUND",
    FINAL_CHOICE = "FINAL_CHOICE",
    PLAY_SAFE = "PLAY_SAFE",
    CHECK_ENVELOPE = "CHECK_ENVELOPE",
    GAMBLE = "GAMBLE",
    GAMBLE_WON = "GAMBLE_WON",
    GAMBLE_LOST = "GAMBLE_LOST",
    ALLIN = "ALLIN",
    ALLIN_WON = "ALLIN_WON",
    ALLIN_LOST = "ALLIN_LOST",
    END_QUIZ = "END_QUIZ",
    SAVE_RESULTS = "SAVE_RESULTS",
    DEBUG = "DEBUG"
}

export default MoneyTreeState;